### ISSUE TITLE
LiHV Battery - Last motor error battery voltage out of bounds

### ISSUE THREAD

**Issue by NFK007** [uavpal/disco-docs#16]
Hi, I am using a Turnigy 3S2P 5200mah LiHV battery - and balance charge to full capacity 4,35v per cell = 13,05v.

I had no error during the first flight, but now after a full charge the Parrot Disco complains with error: Last motor error - battery voltage out of bounds.

I have tried modifying the parameters.conf file, but to no effect.

Anyone have an idea on how to fix?

**Comment by s0ftice** [comment]
Maybe it was not charged fully the first time you tried. Or you charger was set to LiPo instead of LiHV. If you charge it fully as LiHV, the Disco (ESC/Motor) will not accept it. Interestingly, the Bebop2 is ok with it.
There is no software modification you can do, it’s really the hardware refusing... You can try to charge it to “LiPo” max voltage and it will work. Or just get a LiPo instead of LiHV...

**Comment by djoris** [comment]
I finally made explicit in the documentation what s0ftice said above
